server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profile
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
